# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170718_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='has_verified_mobile',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
